/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package siacppt;

/**
 *
 * @author usuario
 */
public class operaciones extends javax.swing.JFrame {

    /**
     * Creates new form operaciones
     */
    public operaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel4 = new org.edisoncor.gui.panel.Panel();
        buttonAqua24 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua25 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua26 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua27 = new org.edisoncor.gui.button.ButtonAqua();
        buttonCircle1 = new org.edisoncor.gui.button.ButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel4.setColorSecundario(new java.awt.Color(255, 255, 255));

        buttonAqua24.setBackground(new java.awt.Color(0, 0, 0));
        buttonAqua24.setText("fase de operaciones");
        buttonAqua24.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        buttonAqua24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua24ActionPerformed(evt);
            }
        });

        buttonAqua25.setBackground(new java.awt.Color(0, 0, 0));
        buttonAqua25.setText("fase de operaciones");
        buttonAqua25.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        buttonAqua25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua25ActionPerformed(evt);
            }
        });

        buttonAqua26.setBackground(new java.awt.Color(0, 0, 0));
        buttonAqua26.setText("predas");
        buttonAqua26.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        buttonAqua26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua26ActionPerformed(evt);
            }
        });

        buttonAqua27.setBackground(new java.awt.Color(0, 0, 0));
        buttonAqua27.setText("maquina");
        buttonAqua27.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        buttonAqua27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua27ActionPerformed(evt);
            }
        });

        buttonCircle1.setText("cancelar");
        buttonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCircle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(buttonAqua24, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buttonAqua26, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGap(9, 9, 9)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAqua27, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAqua25, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(buttonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAqua24, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAqua25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(buttonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAqua26, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAqua27, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAqua24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua24ActionPerformed
        fase a=new fase();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua24ActionPerformed

    private void buttonAqua25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua25ActionPerformed
        operacion a=new operacion();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua25ActionPerformed

    private void buttonAqua26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua26ActionPerformed
           prenda a=new prenda();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua26ActionPerformed

    private void buttonAqua27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua27ActionPerformed
             maquina a=new maquina();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua27ActionPerformed

    private void buttonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCircle1ActionPerformed
       prin v=new prin();
       v.setVisible(true);
       dispose();
    }//GEN-LAST:event_buttonCircle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operaciones().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAqua buttonAqua24;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua25;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua26;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua27;
    private org.edisoncor.gui.button.ButtonCircle buttonCircle1;
    private org.edisoncor.gui.panel.Panel panel4;
    // End of variables declaration//GEN-END:variables
}
