/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package siacppt;

/**
 *
 * @author usuario
 */
public class registro_or_confeccio extends javax.swing.JFrame {

    /**
     * Creates new form registro_or_confeccion
     */
    public registro_or_confeccio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel4 = new org.edisoncor.gui.panel.Panel();
        buttonAqua20 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua21 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua22 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua23 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua24 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua25 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua26 = new org.edisoncor.gui.button.ButtonAqua();
        buttonAqua27 = new org.edisoncor.gui.button.ButtonAqua();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel4.setColorSecundario(new java.awt.Color(255, 255, 255));

        buttonAqua20.setText("bordado");
        buttonAqua20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua20ActionPerformed(evt);
            }
        });

        buttonAqua21.setText("boton");
        buttonAqua21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua21ActionPerformed(evt);
            }
        });

        buttonAqua22.setText("color");
        buttonAqua22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua22ActionPerformed(evt);
            }
        });

        buttonAqua23.setText("hilo");
        buttonAqua23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua23ActionPerformed(evt);
            }
        });

        buttonAqua24.setText("aguja");
        buttonAqua24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua24ActionPerformed(evt);
            }
        });

        buttonAqua25.setText("tallas");
        buttonAqua25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua25ActionPerformed(evt);
            }
        });

        buttonAqua26.setText("cierres");
        buttonAqua26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua26ActionPerformed(evt);
            }
        });

        buttonAqua27.setText("cordon");
        buttonAqua27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAqua27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(buttonAqua22, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAqua23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(buttonAqua21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAqua25, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(buttonAqua27, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(buttonAqua20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonAqua24, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(buttonAqua26, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(buttonAqua24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAqua27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAqua26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAqua20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAqua25, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAqua21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAqua23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAqua22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAqua20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua20ActionPerformed
        bordado a=new bordado();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua20ActionPerformed

    private void buttonAqua21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua21ActionPerformed
        boton a=new boton();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua21ActionPerformed

    private void buttonAqua22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua22ActionPerformed
        color a=new color();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua22ActionPerformed

    private void buttonAqua23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua23ActionPerformed
        hilo a=new hilo();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua23ActionPerformed

    private void buttonAqua24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua24ActionPerformed
        aguja a=new aguja();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua24ActionPerformed

    private void buttonAqua25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua25ActionPerformed
        talla a=new talla();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua25ActionPerformed

    private void buttonAqua26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua26ActionPerformed
        cierres a=new cierres();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua26ActionPerformed

    private void buttonAqua27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAqua27ActionPerformed
        cordon a=new cordon();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAqua27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_or_confeccio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_or_confeccio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_or_confeccio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_or_confeccio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_or_confeccio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAqua buttonAqua20;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua21;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua22;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua23;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua24;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua25;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua26;
    private org.edisoncor.gui.button.ButtonAqua buttonAqua27;
    private org.edisoncor.gui.panel.Panel panel4;
    // End of variables declaration//GEN-END:variables
}
